version: "3.9"
services:

  front:
    container_name: edtech-front
    build: .
    ports:
      - ${PORT}:${PORT}
    volumes:
      - .:/home/edtech-front
      - /home/edtech-front/node_modules
    command: 'npm run serve'